# hexo-theme-indigo
# https://github.com/yscoder/hexo-theme-indigo

# æ·»åŠ æ–°èœå•é¡¹éµå¾ªä»¥ä¸‹è§„åˆ™
# https://fontawesome.com/icons
# menu:
#  link:               fontawesomeå›¾æ ‡ï¼Œçœç•¥å‰ç¼€ï¼Œæœ¬ä¸»é¢˜å‰ç¼€ä¸º icon-ï¼Œå¿…é¡»
#    text: About       èœå•æ˜¾ç¤ºçš„æ–‡å­—ï¼Œå¦‚æœçœç•¥å³é»˜è®¤ä¸å›¾æ ‡ä¸€è‡´ï¼Œé¦–å­—æ¯ä¼šè½¬å¤§å†™
#    url: /about       é“¾æ¥ï¼Œç»å¯¹æˆ–ç›¸å¯¹è·¯å¾„ï¼Œå¿…é¡»ã€‚
#    target: _blank    æ˜¯å¦è·³å‡ºï¼Œçœç•¥åˆ™åœ¨å½“å‰é¡µé¢æ‰“å¼€
menu:
  home:
    text: ä¸»é¡µ
    url: https://zhangbing.site/
  archive:
    text: æ–‡ç« å½’æ¡£
    url: /archives
  shopping-bag:
    text: å°é“º
    url: //store.zhangbing.site/
    target: _blank
  # camera-retro:
  #   text: ç›¸å†Œ
  #   url: //photo.dunizb.com/
  #   target: _blank
  code:
    text: å°ç 
    url: //coding.zhangbing.site/
    target: _blank
  play-circle:
    text: Bç«™
    url: //space.bilibili.com/258420440
    target: _blank
  globe:
    text: å…¬ä¼—å·è®¢é˜…
    url: https://zhangbing.site/#rss
    target: _blank
  rss:
    text: RSSè®¢é˜…
    url: /atom.xml
    target: _blank
  user:
    text: å…³äº
    url: /about

# ä½ çš„å¤´åƒurl
avatar: /img/avatar.gif
# avatar link
avatar_link: /
# å¤´åƒèƒŒæ™¯å›¾
brand: /img/brand.jpg
# favicon
favicon: /favicon.ico

# email
email: dunizb@foxmail.com

# è®¾ç½® Android L Chrome æµè§ˆå™¨çŠ¶æ€æ é¢œè‰²
color: "#3F51B5"

# é¡µé¢æ ‡é¢˜
tags_title: æ ‡ç­¾
archives_title: å½’æ¡£
categories_title: åˆ†ç±»

# æ–‡ç« æˆªæ–­
excerpt_render: true
excerpt_length: 200
excerpt_link: é˜…è¯»å…¨æ–‡ ğŸ§
mathjax: false
archive_yearly: true

# æ˜¯å¦æ˜¾ç¤ºæ–‡ç« æœ€åæ›´æ–°æ—¶é—´
show_last_updated: true

# æ˜¯å¦å¼€å¯åˆ†äº«
share: true

# æ˜¯å¦å¼€å¯æ‰“èµï¼Œå…³é—­ reward: false
reward:
  title: æ„Ÿè°¢æ‚¨çš„æ”¯æŒ
  wechat: /img/wechat.jpg #å¾®ä¿¡ï¼Œå…³é—­è®¾ä¸º false
  alipay: /img/alipay.jpg #æ”¯ä»˜å®ï¼Œå…³é—­è®¾ä¸º false

# æ˜¯å¦å¼€å¯æœç´¢
search: true

# æ˜¯å¦å¤§å±å¹•ä¸‹æ–‡ç« é¡µéšè—å¯¼èˆª
hideMenu: false

# æ˜¯å¦å¼€å¯toc
# toc: false
toc:
  list_number: false # æ˜¯å¦æ˜¾ç¤ºæ•°å­—æ’åº

# æ–‡ç« é¡µç•™è¨€å†…å®¹ï¼Œhexoä¸­æ‰€æœ‰å˜é‡åŠè¾…åŠ©å‡½æ•°ç­‰å‡å¯è°ƒç”¨ï¼Œå…·ä½“è¯·æŸ¥é˜… hexo.io
postMessage: <p>æœ¬æ–‡ä»£è¡¨ä¸ªäººè§‚ç‚¹ï¼Œå†…å®¹ä»…ä¾›å‚è€ƒã€‚è‹¥æœ‰ä¸æ°å½“ä¹‹å¤„ï¼Œæœ›ä¸åèµæ•™ï¼</p> æœ¬æ–‡é“¾æ¥ï¼š<a href="<%- url_for(page.path).replace(/index\.html$/, '') %>" target="_blank" rel="external"><%- page.permalink.replace(/index\.html$/, '') %></a>ã€‚<p style="color:red;">å…³æ³¨å…¬ä¼—å·ï¼Œç¬¬ä¸€æ—¶é—´æ¥æ”¶æœ€æ–°æ–‡ç« ã€‚å¦‚æœå¯¹ä½ æœ‰ä¸€ç‚¹ç‚¹å¸®åŠ©ï¼Œå¯ä»¥ç‚¹å–œæ¬¢ç‚¹èµç‚¹æ”¶è—ï¼Œè¿˜å¯ä»¥å°é¢æ‰“èµä½œè€…ï¼Œä»¥é¼“åŠ±ä½œè€…å†™å‡ºæ›´å¤šæ›´å¥½çš„æ–‡ç« ã€‚</p><img src="https://gitee.com/dunizb/cloudimg/raw/jsdelivr/%E5%85%B3%E6%B3%A8%E5%90%8D%E7%89%87-%E5%A4%A7%E7%A4%BC%E5%8C%85_%E6%A8%AA%E7%89%88%E4%BA%8C%E7%BB%B4%E7%A0%81_2020-01-01-0.jpg" />

# ç«™é•¿ç»Ÿè®¡ï¼Œå¦‚è¦å¼€å¯ï¼Œè¾“å…¥CNZZç«™ç‚¹idï¼Œå¦‚ cnzz: 1255152447
cnzz: false

# ç™¾åº¦ç»Ÿè®¡ï¼Œå¦‚è¦å¼€å¯ï¼Œæ”¹ä¸ºä½ çš„ key
baidu_tongji: e590e40c3f16ace3499cab81c3fa3051

# è…¾è®¯åˆ†æï¼Œå¦‚è¦å¼€å¯ï¼Œè¾“å…¥ç«™ç‚¹id
tajs: false

# google
google_analytics: false
google_site_verification: false

# sogouç«™é•¿éªŒè¯ http://zhanzhang.sogou.com/
sogou_site_verification: false

# less
less:
  compress: true
  paths:
    - source/css/style.less

# ä»¥ä¸‹è¯„è®ºæ’ä»¶å¼€å¯ä¸€ä¸ªå³å¯
# æ˜¯å¦å¼€å¯ disqus
disqus_shortname: false
# æ˜¯å¦å¼€å¯å‹è¨€è¯„è®º, å¡«å†™å‹è¨€ç”¨æˆ·id
uyan_uid: false
# æ˜¯å¦ä½¿ç”¨ gitmentï¼Œhttps://github.com/imsun/gitment
gitment: false
# gitment:
#   owner:
#   repo:
#   client_id:
#   client_secret:

# Valine Comment system. https://valine.js.org
valine:
  enable: true # å¦‚æœä½ æƒ³ä½¿ç”¨valineï¼Œè¯·å°†å€¼è®¾ç½®ä¸º true
  appId: OObzICxguaEmKygmhE2mUp5G-gzGzoHsz # your leancloud appId
  appKey: bBzvsvDvqSr8jOmX6AcoKVhQ # your leancloud appKey
  notify: true # Mail notify
  verify: false # Verify code
  avatar: mm # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  placeholder: Just go go # Comment Box placeholder
  guest_info: nick,mail,link # Comment header info
  pageSize: 10 # comment list page size

# æ˜¯å¦å¼€å¯Hyper Commentsï¼Œå¡«å†™idåˆ™å¯ç”¨ï¼Œfalseåˆ™ç¦ç”¨ã€‚http://hypercomments.com
# Hyper Comments support. Write your id here, or false to disable
hyper_id: false

# è§„èŒƒç½‘å€
# è®©æœç´¢å¼•æ“é‡å®šå‘ä½ çš„ä¸åŒåŸŸåã€ä¸åŒå­åŸŸã€åŒåŸŸä¸åŒç›®å½•çš„ç«™ç‚¹åˆ°ä½ æœŸæœ›çš„è·¯å¾„
# https://support.google.com/webmasters/answer/139066
# å‡è®¾é…ç½®ä¸º canonical: http://imys.netï¼Œé‚£ä¹ˆä»æœç´¢å¼•æ“ä¸­ www.imys.net è¿›å…¥ä¼šé‡å®šå‘åˆ° imys.net
canonical: true

# ç‰ˆæƒèµ·å§‹å¹´ä»½
since_year: 2019

# ç”¨æˆ·é¡µé¢ä¸­ä½œè€…ç›¸å…³çš„æè¿°æ€§æ–‡å­—ï¼Œå¦‚ä¸éœ€è¦è®¾ä¸º false
about: å‰ç«¯å¼€å‘

# â€œä¸è’œå­â€è®¿é—®é‡ç»Ÿè®¡ï¼Œè¯¦è§ http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  site_uv: ç«™ç‚¹æ€»è®¿å®¢æ•°ï¼š
  site_pv: ç«™ç‚¹æ€»è®¿é—®é‡ï¼š

# åŠ¨æ€å®šä¹‰title
title_change:
  normal: (ã¤ã‚§âŠ‚)å’¦!åˆå¥½äº†!
  leave: æ­»é¬¼å»å“ªé‡Œäº†ï¼

# è®¾ç½®ä¸º true å‘å¸ƒåå°†ä½¿ç”¨ unpkg cdn æœ€æ–°çš„ä¸»é¢˜æ ·å¼
# å¦‚æœæƒ³è®©ä½ çš„è‡ªå®šä¹‰æ ·å¼ç”Ÿæ•ˆï¼ŒæŠŠæ­¤é¡¹è®¾ä¸º false
cdn: true

# è®¾ç½®ä¸º true å°†ä½¿ç”¨ lightbox render å›¾ç‰‡
lightbox: true

# icpå¤‡æ¡ˆå·  ICP_license: äº¬ICPå¤‡1234556å·-1
ICP_license: false
